//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voice_Coding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voice_Coding.DataResource", typeof(DataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_tray_b_w {
            get {
                object obj = ResourceManager.GetObject("icon_tray_b_w", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;VoiceCoding&gt;
        ///	
        ///	&lt;HeaderFiles name=&quot;Path&quot; value=&quot;C:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\10\\include&quot;/&gt;
        ///	
        ///	&lt;Namespace name=&quot;Standard&quot; value=&quot;std&quot;/&gt;
        ///	
        ///	&lt;Datatype name=&quot;integer&quot; value=&quot;int&quot;/&gt;
        ///	&lt;Datatype name=&quot;int&quot; value=&quot;int&quot;/&gt;
        ///	&lt;Datatype name=&quot;boolean&quot; value=&quot;bool&quot;/&gt;
        ///	&lt;Datatype name=&quot;bool&quot; value=&quot;bool&quot;/&gt;
        ///	&lt;Datatype name=&quot;float&quot; value=&quot;float&quot;/&gt;
        ///	&lt;Datatype name=&quot;floating point&quot; value=&quot;float&quot;/&gt;
        ///	&lt;Datatype name=&quot;double&quot; value=&quot;double&quot;/&gt;
        ///	&lt;Datatype name=&quot;voi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainResource {
            get {
                return ResourceManager.GetString("MainResource", resourceCulture);
            }
        }
    }
}
