//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voice_Coding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voice_Coding.DataResource", typeof(DataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello
        ///undo
        ///up
        ///down
        ///left
        ///right
        ///newline
        ///tab
        ///erase
        ///clear
        ///back
        ///stop
        ///exit.
        /// </summary>
        public static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void:void
        ///integer:int
        ///int:int
        ///char:char
        ///character:char
        ///boolean:bool
        ///float:float
        ///double:double
        ///input_output_stream:iostream
        ///io_stream:iostream
        ///standard_lib:cstdlib
        ///stdlib:cstdlib
        ///maths:cmaths
        ///string:cout&lt;&lt;&quot;&quot;&lt;&lt;;
        ///var:cout&lt;&lt;&lt;&lt;endl;
        ///variable:cout&lt;&lt;&lt;&lt;endl;
        ///standard:std
        ///code_recognition:CodeRecognition.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATATYPE{
        ///void
        ///integer
        ///int
        ///char
        ///character
        ///boolean
        ///float
        ///double
        ///}
        ///
        ///HEADERFILES{
        ///io_stream
        ///input_output_stream
        ///standard_lib
        ///stdlib
        ///maths
        ///string
        ///code_recognition
        ///}
        ///
        ///PRINTSTYLE{
        ///print_line
        ///print
        ///}
        ///
        ///PRINTVALUE{
        ///var
        ///variable
        ///string
        ///}
        ///
        ///NAMESPACE{
        ///standard
        ///}.
        /// </summary>
        public static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_tray_b_w {
            get {
                object obj = ResourceManager.GetObject("icon_tray_b_w", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
